version: "3.8"
services:
  sdkpt-ml:
    image: sdkpt-ml # Replace with the actual image name or image path
    container_name: sdkpt-ml
    ports:
      - "8000:8000"
    environment:
      - BACKEND_CORS_ORIGINS=["*", "http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080"]
      - PROJECT_NAME="SDKPT ML API"
