"""initial

Revision ID: 81e91c9ca30b
Revises: 
Create Date: 2024-05-14 14:58:14.394136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e91c9ca30b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fasyankes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('ownership', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fasyankes_code'), 'fasyankes', ['code'], unique=False)
    op.create_index(op.f('ix_fasyankes_id'), 'fasyankes', ['id'], unique=False)
    op.create_index(op.f('ix_fasyankes_name'), 'fasyankes', ['name'], unique=False)
    op.create_table('intervention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kelurahan_name', sa.String(length=255), nullable=False),
    sa.Column('puskesmas_id', sa.Integer(), nullable=True),
    sa.Column('intervention_1', sa.Text(), nullable=True),
    sa.Column('intervention_2', sa.Text(), nullable=True),
    sa.Column('intervention_3', sa.Text(), nullable=True),
    sa.Column('intervention_4', sa.Text(), nullable=True),
    sa.Column('intervention_5', sa.Text(), nullable=True),
    sa.Column('intervention_6', sa.Text(), nullable=True),
    sa.Column('intervention_7', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervention_id'), 'intervention', ['id'], unique=False)
    op.create_index(op.f('ix_intervention_kelurahan_name'), 'intervention', ['kelurahan_name'], unique=False)
    op.create_table('kecamatan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kecamatan_id'), 'kecamatan', ['id'], unique=False)
    op.create_index(op.f('ix_kecamatan_name'), 'kecamatan', ['name'], unique=False)
    op.create_table('kelurahan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_kd', sa.String(length=255), nullable=True),
    sa.Column('kelurahan_name', sa.String(length=255), nullable=False),
    sa.Column('puskesmas_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kelurahan_id'), 'kelurahan', ['id'], unique=False)
    op.create_index(op.f('ix_kelurahan_kelurahan_name'), 'kelurahan', ['kelurahan_name'], unique=False)
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kelurahan_domisili', sa.String(length=255), nullable=True),
    sa.Column('kode_fasyankes', sa.String(length=255), nullable=True),
    sa.Column('tahun', sa.Integer(), nullable=True),
    sa.Column('bulan', sa.Integer(), nullable=True),
    sa.Column('tipe_diagnosis', sa.String(length=255), nullable=True),
    sa.Column('anatomi_tb', sa.String(length=255), nullable=True),
    sa.Column('riwayat_hiv', sa.String(length=255), nullable=True),
    sa.Column('riwayat_dm', sa.String(length=255), nullable=True),
    sa.Column('panduan_obat', sa.String(length=255), nullable=True),
    sa.Column('sumber_obat', sa.String(length=255), nullable=True),
    sa.Column('status_pengobatan', sa.String(length=255), nullable=True),
    sa.Column('pengobatan_terakhir', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_id'), 'patient', ['id'], unique=False)
    op.create_table('puskesmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puskesmas_code'), 'puskesmas', ['code'], unique=False)
    op.create_index(op.f('ix_puskesmas_id'), 'puskesmas', ['id'], unique=False)
    op.create_index(op.f('ix_puskesmas_name'), 'puskesmas', ['name'], unique=False)
    op.create_table('semar_betul_auth',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semar_betul_auth_access_token'), 'semar_betul_auth', ['access_token'], unique=False)
    op.create_index(op.f('ix_semar_betul_auth_id'), 'semar_betul_auth', ['id'], unique=False)
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('bulan', sa.Integer(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('kelurahan_id', sa.Integer(), nullable=False),
    sa.Column('kelurahan_name', sa.String(length=255), nullable=False),
    sa.Column('population_density', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('tb_cases', sa.Integer(), nullable=True),
    sa.Column('population_tb_cases_ratio', sa.Float(), nullable=True),
    sa.Column('dm_cases', sa.Integer(), nullable=True),
    sa.Column('jumlah_klinik_pratama', sa.Integer(), nullable=True),
    sa.Column('jumlah_klinik_utama', sa.Integer(), nullable=True),
    sa.Column('gender_perempuan', sa.Integer(), nullable=True),
    sa.Column('gender_laki_laki', sa.Integer(), nullable=True),
    sa.Column('usia_paruh_baya', sa.Integer(), nullable=True),
    sa.Column('usia_pensiun', sa.Integer(), nullable=True),
    sa.Column('usia_pekerja_awal', sa.Integer(), nullable=True),
    sa.Column('usia_lanjut', sa.Integer(), nullable=True),
    sa.Column('usia_muda', sa.Integer(), nullable=True),
    sa.Column('usia_pra_pensiun', sa.Integer(), nullable=True),
    sa.Column('usia_anak', sa.Integer(), nullable=True),
    sa.Column('pendidikan_diploma', sa.Integer(), nullable=True),
    sa.Column('pendidikan_s1', sa.Integer(), nullable=True),
    sa.Column('pendidikan_s2_s3', sa.Integer(), nullable=True),
    sa.Column('pendidikan_tamat_sd', sa.Integer(), nullable=True),
    sa.Column('pendidikan_tamat_sma', sa.Integer(), nullable=True),
    sa.Column('pendidikan_tamat_smp', sa.Integer(), nullable=True),
    sa.Column('pendidikan_tidak_sekolah', sa.Integer(), nullable=True),
    sa.Column('pendidikan_tidak_tamat_sd', sa.Integer(), nullable=True),
    sa.Column('status_bekerja_tidak_bekerja', sa.Integer(), nullable=True),
    sa.Column('status_bekerja_bekerja', sa.Integer(), nullable=True),
    sa.Column('pendapatan_keluarga_kategori_1', sa.Integer(), nullable=True),
    sa.Column('pendapatan_keluarga_kategori_2', sa.Integer(), nullable=True),
    sa.Column('pendapatan_keluarga_kategori_3', sa.Integer(), nullable=True),
    sa.Column('pendapatan_keluarga_kategori_4', sa.Integer(), nullable=True),
    sa.Column('pendapatan_keluarga_kategori_5', sa.Integer(), nullable=True),
    sa.Column('tpt_serumah_tidak_mendapatkan_tpt', sa.Integer(), nullable=True),
    sa.Column('tpt_serumah_tidak_ada', sa.Integer(), nullable=True),
    sa.Column('tpt_serumah_ada', sa.Integer(), nullable=True),
    sa.Column('perokok_aktif_tidak', sa.Integer(), nullable=True),
    sa.Column('perokok_aktif_ya', sa.Integer(), nullable=True),
    sa.Column('konsumsi_alkohol_tidak', sa.Integer(), nullable=True),
    sa.Column('konsumsi_alkohol_ya', sa.Integer(), nullable=True),
    sa.Column('kategori_pengetahuan_cukup', sa.Integer(), nullable=True),
    sa.Column('kategori_pengetahuan_kurang', sa.Integer(), nullable=True),
    sa.Column('kategori_pengetahuan_baik', sa.Integer(), nullable=True),
    sa.Column('kategori_pengetahuan_buruk', sa.Integer(), nullable=True),
    sa.Column('kategori_literasi_problematic', sa.Integer(), nullable=True),
    sa.Column('kategori_literasi_excellent', sa.Integer(), nullable=True),
    sa.Column('kategori_literasi_inadequate', sa.Integer(), nullable=True),
    sa.Column('kategori_literasi_sufficient', sa.Integer(), nullable=True),
    sa.Column('kategori_stigma_tinggi', sa.Integer(), nullable=True),
    sa.Column('kategori_stigma_sedang', sa.Integer(), nullable=True),
    sa.Column('kategori_stigma_rendah', sa.Integer(), nullable=True),
    sa.Column('kategori_stigma_tidak', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_bulan'), 'survey', ['bulan'], unique=False)
    op.create_index(op.f('ix_survey_created_at'), 'survey', ['created_at'], unique=False)
    op.create_index(op.f('ix_survey_id'), 'survey', ['id'], unique=False)
    op.create_index(op.f('ix_survey_kelurahan_id'), 'survey', ['kelurahan_id'], unique=False)
    op.create_index(op.f('ix_survey_kelurahan_name'), 'survey', ['kelurahan_name'], unique=False)
    op.create_index(op.f('ix_survey_tahun'), 'survey', ['tahun'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_tahun'), table_name='survey')
    op.drop_index(op.f('ix_survey_kelurahan_name'), table_name='survey')
    op.drop_index(op.f('ix_survey_kelurahan_id'), table_name='survey')
    op.drop_index(op.f('ix_survey_id'), table_name='survey')
    op.drop_index(op.f('ix_survey_created_at'), table_name='survey')
    op.drop_index(op.f('ix_survey_bulan'), table_name='survey')
    op.drop_table('survey')
    op.drop_index(op.f('ix_semar_betul_auth_id'), table_name='semar_betul_auth')
    op.drop_index(op.f('ix_semar_betul_auth_access_token'), table_name='semar_betul_auth')
    op.drop_table('semar_betul_auth')
    op.drop_index(op.f('ix_puskesmas_name'), table_name='puskesmas')
    op.drop_index(op.f('ix_puskesmas_id'), table_name='puskesmas')
    op.drop_index(op.f('ix_puskesmas_code'), table_name='puskesmas')
    op.drop_table('puskesmas')
    op.drop_index(op.f('ix_patient_id'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_kelurahan_kelurahan_name'), table_name='kelurahan')
    op.drop_index(op.f('ix_kelurahan_id'), table_name='kelurahan')
    op.drop_table('kelurahan')
    op.drop_index(op.f('ix_kecamatan_name'), table_name='kecamatan')
    op.drop_index(op.f('ix_kecamatan_id'), table_name='kecamatan')
    op.drop_table('kecamatan')
    op.drop_index(op.f('ix_intervention_kelurahan_name'), table_name='intervention')
    op.drop_index(op.f('ix_intervention_id'), table_name='intervention')
    op.drop_table('intervention')
    op.drop_index(op.f('ix_fasyankes_name'), table_name='fasyankes')
    op.drop_index(op.f('ix_fasyankes_id'), table_name='fasyankes')
    op.drop_index(op.f('ix_fasyankes_code'), table_name='fasyankes')
    op.drop_table('fasyankes')
    # ### end Alembic commands ###
