"""added new models

Revision ID: ea898f5731a0
Revises: 08d11e076d57
Create Date: 2024-04-29 22:17:38.768807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea898f5731a0'
down_revision: Union[str, None] = '08d11e076d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interventions_id', table_name='interventions')
    op.drop_index('ix_interventions_kelurahan_name', table_name='interventions')
    op.drop_table('interventions')
    op.drop_index('ix_surveys_created_at', table_name='surveys')
    op.drop_index('ix_surveys_id', table_name='surveys')
    op.drop_index('ix_surveys_kelurahan_id', table_name='surveys')
    op.drop_index('ix_surveys_kelurahan_name', table_name='surveys')
    op.drop_table('surveys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('kelurahan_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kelurahan_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('population_density', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('population', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tb_cases', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('population_tb_cases_ratio', mysql.FLOAT(), nullable=True),
    sa.Column('dm_cases', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('jumlah_klinik_pratama', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('jumlah_klinik_utama', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender_perempuan', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender_laki_laki', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usia_paruh_baya', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usia_pensiun', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usia_pekerja_awal', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usia_lanjut', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usia_muda', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usia_pra_pensiun', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usia_anak', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pendidikan_diploma', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pendidikan_s1', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pendidikan_s2_s3', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pendidikan_tamat_sd', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pendidikan_tamat_sma', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pendidikan_tamat_smp', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pendidikan_tidak_sekolah', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pendidikan_tidak_tamat_sd', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_bekerja_tidak_bekerja', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_bekerja_bekerja', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pendapatan_keluarga_kategori_1', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pendapatan_keluarga_kategori_2', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pendapatan_keluarga_kategori_3', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pendapatan_keluarga_kategori_4', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pendapatan_keluarga_kategori_5', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tpt_serumah_tidak_mendapatkan_tpt', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tpt_serumah_tidak_ada', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tpt_serumah_ada', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('perokok_aktif_tidak', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('perokok_aktif_ya', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('konsumsi_alkohol_tidak', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('konsumsi_alkohol_ya', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kategori_pengetahuan_cukup', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kategori_pengetahuan_kurang', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kategori_pengetahuan_baik', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kategori_pengetahuan_buruk', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kategori_literasi_problematic', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kategori_literasi_excellent', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kategori_literasi_inadequate', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kategori_literasi_sufficient', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kategori_stigma_tinggi', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kategori_stigma_sedang', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kategori_stigma_rendah', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kategori_stigma_tidak', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_surveys_kelurahan_name', 'surveys', ['kelurahan_name'], unique=False)
    op.create_index('ix_surveys_kelurahan_id', 'surveys', ['kelurahan_id'], unique=False)
    op.create_index('ix_surveys_id', 'surveys', ['id'], unique=False)
    op.create_index('ix_surveys_created_at', 'surveys', ['created_at'], unique=False)
    op.create_table('interventions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kelurahan_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('puskesmas_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('intervention_1', mysql.TEXT(), nullable=True),
    sa.Column('intervention_2', mysql.TEXT(), nullable=True),
    sa.Column('intervention_3', mysql.TEXT(), nullable=True),
    sa.Column('intervention_4', mysql.TEXT(), nullable=True),
    sa.Column('intervention_5', mysql.TEXT(), nullable=True),
    sa.Column('intervention_6', mysql.TEXT(), nullable=True),
    sa.Column('intervention_7', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_interventions_kelurahan_name', 'interventions', ['kelurahan_name'], unique=False)
    op.create_index('ix_interventions_id', 'interventions', ['id'], unique=False)
    # ### end Alembic commands ###
